version: '3.8'

services:
  web:
    build: .
    container_name: webarchive_django
    networks:
      - proxy
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://webarchive:password@db:5432/webarchive
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - archive_storage:/app/archives

  db:
    image: postgres:15
    container_name: webarchive_db
    networks:
      - proxy
    environment:
      - POSTGRES_DB=webarchive
      - POSTGRES_USER=webarchive
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: webarchive_redis
    networks:
      - proxy

  worker:
    build: .
    container_name: webarchive_worker
    command: celery -A webarchive worker -l info
    networks:
      - proxy
    environment:
      - DATABASE_URL=postgresql://webarchive:password@db:5432/webarchive
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - archive_storage:/app/archives

volumes:
  postgres_data:
  archive_storage:

networks:
  proxy:
    external: true