version: '3.8'

services:
  web:
    build: .
    container_name: webarchive_django
    ports:
      - "8000:8000"
    networks:
      - proxy
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=webarchive
      - DB_USER=webarchive
      - DB_PASSWORD=password
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
    volumes:
      - ./backend:/app
      - ./frontend:/app
      - archive_storage:/app/archives
      - ./frontend:/app

  db:
    image: postgres:16
    container_name: webarchive_db
    networks:
      - proxy
    environment:
      - POSTGRES_DB=webarchive
      - POSTGRES_USER=webarchive
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: webarchive_redis
    networks:
      - proxy

  worker:
    build: .
    container_name: webarchive_worker
    command: celery -A webarchive worker -l info
    networks:
      - proxy
    environment:
      - DB_HOST=db
      - DB_NAME=webarchive
      - DB_USER=webarchive
      - DB_PASSWORD=password
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - archive_storage:/app/archives

volumes:
  postgres_data:
  archive_storage:

networks:
  proxy:
    external: true